### ISSUE TITLE
where to find the following csv file, thanks.

### ISSUE THREAD

**Issue by liamxg** [wlhamilton/SARSCoV2-global-sequence-distribution#1]
seq_demographic_data <- read.csv("sequence_counts_with_population_GDP_income_continets.csv")

**Comment by LiXingguangBrandonStark** [comment]
could you please give me an example, thanks.

**Comment by LiXingguangBrandonStark** [comment]
Error in st_cast.POINT(x[[1]], to, ...) : 
  cannot create MULTILINESTRING from POINT
In addition: Warning message:
In st_cast.GEOMETRYCOLLECTION(X[[i]], ...) :
  only first part of geometrycollection is retained

**Comment by LiXingguangBrandonStark** [comment]
when i run ggplot(data = world) +
  geom_sf() +
  coord_sf(xlim = c(-20, 53), ylim = c(-36, 38.5), expand = FALSE) +
  geom_point(data=data_plot_test, aes(x=latitude, y=longitude, size=sequence_count, color=Income.group)) +
  scale_size(range = c(1, 20), breaks = c(0,3000), name="Sequences") +
  scale_color_brewer(palette="Set2"), i tells me error.
